### ISSUE TITLE
Multiple divs with "mwl-resizable" end up in resizing all at the same moment

### ISSUE THREAD

**Issue by paulleyten** [mattlewis92/angular2-resizable#15]
Whe creating multiple resizable DIVS like this:

`<div *ngFor="let hero of heroes; let index=index;">
    <div class="{{index}} rectangle" [ngStyle]="style[index]" mwl-resizable [validateResize]="validate" [resizeEdges]="{right: true,  left: true}"
        [enableResizeStyling]="true" [resizeSnapGrid]="{left: 50, right: 50}" (onResizeEnd)="onResizeEnd($event, index)">
        {{index}}
    </div>
</div>
`

it Ends up that all the divs resize all together at once..

**Comment by mattlewis92** [comment]
Ah damn, I hadn't tested this with resizing multiple elements. Using position: fixed was a bad idea as it removes the element from the document flow so other elements below then overlap it as they shift up. I'll try and find some time over the weekend to fix it, thanks for the bug report! 😄

**Comment by paulleyten** [comment]
At your service ☺

Schöne Grüße,

Paul Leijten

[cid:image002.jpg@01D1DDE9.83131780]
Computer Total
A-6364 Brixen im Thale
T: 05334 / 20 380
E: info@computertotal.at<mailto:info@computertotal.at>
W: http://wwww.computertotal.at


Von: Matt Lewis [mailto:notifications@github.com]
Gesendet: Donnerstag, 14. Juli 2016 16:04
An: mattlewis92/angular2-resizable <angular2-resizable@noreply.github.com>
Cc: Paul Leijten <info@computertotal.at>; Author <author@noreply.github.com>
Betreff: Re: [mattlewis92/angular2-resizable] Multiple divs with "mwl-resizable" end up in resizing all at the same moment (#15)


Ah damn, I hadn't tested this with resizing multiple elements. Using position: fixed was a bad idea as it removes the element from the document flow so other elements below then overlap it as they shift up. I'll try and find some time over the weekend to fix it, thanks for the bug report! &#128516;

**Comment by mattlewis92** [comment]
Should be fixed in 0.2.0, thanks for reporting! 😄
