### ISSUE TITLE
this.mousedown.flatMap is not a function  EXCEPTION when running the sample on the QuickStart

### ISSUE THREAD

**Issue by jgsacris** [mattlewis92/angular2-resizable#16]
When trying the example with the Angular2 Quick Start I keep getting the following error:

`EXCEPTION: TypeError: this.mousedown.flatMap is not a function`

located at: node_modules/angular2-resizable/angular2-resizable.js:365:41

The strange thing the that when running through the debugger I can see that the mousedown property is initialised correctly as a Subject.
I am  using angular 2.0.0-rc.5

**Comment by mattlewis92** [comment]
Oops, looks like there was an error with the webpack build config, should be fixed now in 0.3.1!
