### ISSUE TITLE
Demo does not work in IE 11 on Windows 8.1 x64

### ISSUE THREAD

**Issue by hhubik** [mattlewis92/angular2-resizable#17]
Hangs at the "Loading ... " message.

**Comment by mattlewis92** [comment]
Are there any errors logged in the console that might help?

**Comment by hhubik** [comment]
File: demo
SCRIPT438: Object doesn't support property or method 'keys'
File: demo.js, Line: 2032, Column: 1012

Not sure if this applies in this case, but I have seen other Angular2 apps having an issue with IE that got solved by using a polyfill as explained for example here
https://angular.io/docs/ts/latest/quickstart.html#!#index

**Comment by mattlewis92** [comment]
Looks like I'd forgotten to import the es6-shim module, should be fixed now (I only have a mac so can't say for sure)

**Comment by hhubik** [comment]
Just tried it in IE11 on my Windows box.  Looks good. Thanks.
