### ISSUE TITLE
Dragging the right edge of the Demo rectangle selects part of the page heading

### ISSUE THREAD

**Issue by hhubik** [mattlewis92/angular2-resizable#18]
I see this issue in Chrome Version 52.0.2743.116 m (64-bit), but not in Firefox.

1. Go to the Demo page.
2. Drag the right edge of the red rectangle to the left by grabbing the edge roughly in its middle.
3. Part of the page heading (roughly corresponding to the distance the edge was moved) is highlighted as shown below.  Notice that the "resizable" icon in the bottom right corner of the rectangle is also selected even though it was **not** used to re-size the rectangle ![angular2resizable](https://cloud.githubusercontent.com/assets/14813201/18057288/59006ff4-6ddd-11e6-9261-979225ca6a25.PNG)

**Comment by mattlewis92** [comment]
I would suggest adding this as a rule when you being resizing: http://stackoverflow.com/questions/826782/how-to-disable-text-selection-highlighting-using-css

e.g. 

```
* {
  // apply this on the (resizeStart) output and remove on (resizeEnd)
  user-select: none;
}
```

**Comment by hhubik** [comment]
That sounds good.  Thanks. (I assume you meant to say "begin resizing" ;)

**Comment by mattlewis92** [comment]
Ah yeah my bad, typing too fast 😉
