### ISSUE TITLE
Not on NPM?

### ISSUE THREAD

**Issue by ivanmayes** [mattlewis92/angular2-resizable#7]
Looks like this is no longer on npm, is that intentional?

**Comment by mattlewis92** [comment]
I've not yet published it to npm as I've not finished writing the module yet, I need to clean up the codebase a bit more first and then I'll cut an initial 0.1.0 release. I'm aiming for sometime this week 😄

**Comment by ivanmayes** [comment]
Gotcha!  Going to watch for this.

**Comment by mattlewis92** [comment]
I've just published an initial version to npm, there are still a [few bugs and features](https://github.com/mattlewis92/angular2-resizable/issues) to be worked on which I'll try and get sorted in the next week or so. LMK if you have any issues 😄
